### PR TITLE
Adding scaphold

### PR DESCRIPTION
**Pull request by vning93**
Scaphold Slackr GraphQL API!

🎉 🎉 🎉

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@vning93 Thank you for contribution and sorry for delay.
Your example is great since it is the only API in our collection that supports subscriptions.
I need to make a few changes to your commit before merge, will try to make it today.

**Comment by IvanGoncharov** [comment]
@vning93 I added Slarck to this section:
https://github.com/APIs-guru/graphql-apis#demonstration-only-apis
Since it only example API.

**Comment by IvanGoncharov** [comment]
@vning93 Sorry for huge delay :(

**Comment by vning93** [comment]
No problem, thanks for the add!

**Pull request closed without merging**
